import numpy as np
import matplotlib.pyplot as plt
import math

# (1) Define basic functions in the desired algebra (generated by R[x]/<x^2 - ax - b>)

def square(z,a,b):
    result = [z[0]**2 + b*z[1]**2, 2*z[0]*z[1] + a*z[1]**2]
    return [z[0]**2 + b*z[1]**2, 2*z[0]*z[1] + a*z[1]**2]

def zi(c,a,b,i):
    zn = [0,0]
    for k in range(i):
        zn = f_c(zn,c,a,b)
    return(zn)

def add(z1,z2):
    return [z1[0]+z2[0],z1[1]+z2[1]]

def abs(z):
    return(z[0]**2+z[1]**2)
    
def f_c(z,c,a,b):
    return add(square(z,a,b),c)

# (2) Define the divergence tester

def test(c,a,b,i):
    z0 = zi(c,a,b,i)
    z1 = f_c(z0,c,a,b)
    if abs(z1) == 0:
        return -1
    else:
        return abs(z0)/abs(z1)

# (3) Create a binary array of points that do and do not diverge

def gridder(n,k,xmin,xmax,a,b):
    global grid
    grid = []
    for i in range(0,k):
        row = []
        yval = xmin + i*(xmax - xmin)/k
        for j in range(0,k):
            xval = xmin + j*(xmax - xmin)/k
            try:
                if test([xval,yval],a,b,n)<1.7:
                    row.append(-1)
                else:
                    row.append(1)
            except OverflowError or ZeroDivisionError:
                row.append(1)
        grid.append(row)
    return grid

# (4) Plot the binary array generated in (3)

def plotter(n,k,xmin,xmax,a,b,name):
    grid = np.array(gridder(n,k,xmin,xmax,a,b))
    plt.imshow(grid,cmap = 'gray',extent=[xmin,xmax,xmin,xmax])
    plt.savefig(name,bbox_inches='tight')
    
# The following commented code will generate the Mandelbrot set in the three main 2D algebras:    
# plotter(30000,150,-2,2,0,-1,'M(0,-1) (Complex)')
# plotter(30000,150,-2,2,0,1,'M(0,1) (Hyperbolic)')
# plotter(30000,150,-2,2,0,0,'M(0,0) (Dual)')

# (5) Iterate the Mandelbrot set from R[x]/<x^2 - t> from t = -1 (Hyperbolic) to t = 1 (Complex)

steps = 60
for i in range(0,steps):
    name = 'M(0,-1 + 2*' + str(i) + '/' + str(steps) + ')'
    #plotter(30000,150, -2, 2, 0, -1 + 2*i/steps, name)
    #print(i)
    
for i in range(0,steps):
    name = 'M(0, -1/30 + 2*' + str(i) + '/[30*' + str(steps) + '])'
    plotter(30000, 150, -2, 2, 0, -1/30 + 2*i/(30*steps), name)
    print(i)
